### ISSUE TITLE
To-do list Mar 20 2018

### ISSUE THREAD

**Issue by MeaghanShaw** [ReproducibleQM/waterworld#1]
- [x] Edit readme

- [x] creative commons license

- [ ] Figure out what we want to actually include in our results

- [ ] Graph results

- [x] Code of conduct

- [ ] Contributors

**Comment by MeaghanShaw** [comment]
- [ ] Code of conduct
